// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilLc11LyS5QlN86gC4n7ykqBh6supCUo',
    appId: '1:952355362314:web:44c51a62dceea0924ab1f3',
    messagingSenderId: '952355362314',
    projectId: 'evently-ee39b',
    authDomain: 'evently-ee39b.firebaseapp.com',
    storageBucket: 'evently-ee39b.firebasestorage.app',
    measurementId: 'G-N6E3E512H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-72A7HBHKhm6XaOoLSOUVcJjWPmBtiw4',
    appId: '1:952355362314:android:820d0cd31563dfe74ab1f3',
    messagingSenderId: '952355362314',
    projectId: 'evently-ee39b',
    storageBucket: 'evently-ee39b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgIQJ46j3dTb8S1YOkAErYkJCLC2RD8pw',
    appId: '1:952355362314:ios:fb4be1605877c8594ab1f3',
    messagingSenderId: '952355362314',
    projectId: 'evently-ee39b',
    storageBucket: 'evently-ee39b.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgIQJ46j3dTb8S1YOkAErYkJCLC2RD8pw',
    appId: '1:952355362314:ios:fb4be1605877c8594ab1f3',
    messagingSenderId: '952355362314',
    projectId: 'evently-ee39b',
    storageBucket: 'evently-ee39b.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAilLc11LyS5QlN86gC4n7ykqBh6supCUo',
    appId: '1:952355362314:web:9b5708d14cc619b04ab1f3',
    messagingSenderId: '952355362314',
    projectId: 'evently-ee39b',
    authDomain: 'evently-ee39b.firebaseapp.com',
    storageBucket: 'evently-ee39b.firebasestorage.app',
    measurementId: 'G-0CNQQ9ZT79',
  );
}
